#triggers
good_night:
  name: Good Night
  initial: off

good_morning:
  name: Good Morning
  initial: off

meal_time:
  name: Meal Time
  initial: off

tv_time:
  name: TV Time
  initial: off

work:
  name: Work
  initial: off

flash:
  name: Flash
  initial: off

guard_dog:
  name: Guard Dog
  initial: off
