>-
  {%- macro moon() -%}
    {%- if states.sensor.moon.state == 'Full moon' -%}
      {{ [
           "Check out the full moon tonight!",
           "Hey look, There is the full moon. ",
           "The moon is huge! And full. ",
           "If you want to see the full moon tonight is the night."
           ] | random }}
    {%- endif -%}
  {%- endmacro -%}

  {# a macro that removes all newline characters, empty spaces, and returns formatted text and replaces underscores with spaces  #}
  {%- macro cleanup(data) -%}
    {%- for item in data.split("\n")  if item | trim != "" -%}
    {{ item | trim | replace("_", " ") }} {% endfor -%}
  {%- endmacro -%}

  {# ********************************************* #}
  {#  ******** Start the Speech routines ********  #}
  {# ********************************************* #}

  {# a macro to call all macros :)  #}
  {%- macro mother_of_all_macros() -%}

    {% if call_no_announcement != 1 %}
      {% if now().strftime('%H')|int(9999)< 12 and now().strftime('%H')|int(9999)> 6 %}
          Good morning.
      {% elif now().strftime('%H')|int(9999)>= 12 and now().strftime('%H')|int(9999)< 17 %}
          Good afternoon.
      {% else %}
          Good evening.
      {% endif %}
    {% endif %}

    {# Called from Annoucenments #}
    {{ personarriving | default }}

    {{ NewDevice | default }}

    {% if value1 is not none %}
    {{ value1 | default }}
    {% endif %}

    {# call a Random fact about the house #}
    {{ ([moon, days_until]|random)() }}

  {%- endmacro -%}
  {{- cleanup(mother_of_all_macros()) -}}
