- id: '1677190367431'
  alias: Welcome Home
  description: Whenever a Family member comes home, trigger stuff...
  trigger:
  - platform: state
    entity_id:
    - person.boris
    from: not_home
    to: home
  - platform: state
    entity_id:
    - person.hannah
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: sun
      after: sunset
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.woonkamer
  mode: restart
- id: '1677194632277'
  alias: Guest Mode Audio feedback
  description: Notify the house that Guest mode has been enabled.
  trigger:
  - platform: state
    entity_id:
    - input_boolean.guest_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.speech_engine
    data:
      value1: '{{ [ "Guest Mode has been enabled for the rest of the day.", "Switching
        to guest mode! ", "I have enabled guest mode for the rest of the day. ", "System
        Guest Mode has been enabled. I will minimize the amount of automation for
        today.", "Look but do not touch mode enabled.  Otherwise known as Guest Mode
        around here.", "Guest mode enabled or as I like to call it, Look but do not
        touch mode.", "Awesome! I will take the rest of the day off.  Guest mode has
        been enabled.", "Guest Mode enabled.  In other words, Manual Mode engaged.",
        "Guest mode enabled.  Have Fun!", "Family, Friends and Fun.  Guest mode has
        been enabled today.", "Guest Mode enabled.  I am still doing stuff behind
        the scenes but probably will not turn off the lights on you." ] | random }}

        '
      call_responsibilities: 1
      call_no_announcement: 1
  mode: single
- id: '1677194733697'
  alias: Guest Mode Reset
  description: Notify the user Guest Mode has been disabled.
  trigger:
  - platform: state
    entity_id:
    - group.family
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.guest_mode
  - service: script.speech_engine
    data:
      value1: '{{ [ "Guest Mode has been disabled and normal automations will continue.",
        "Let me disable guest mode since there are no longer any guests in the house.
        ", "I have disabled guest mode and have resumed normal operations! ", "Disabling
        guest mode! " ] | random }}

        '
      call_no_announcement: 1
  mode: single
- id: '1677195215202'
  alias: TV Time
  description: Turns off TV Lights and other actions when the TV is turned in the
    evening.
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - media_player.samsung_7_series_50
    from: 'off'
    to: 'on'
  - platform: time
    at: '20:00:00'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: time
      after: '20:00:00'
      before: 08:00:00
    - condition: state
      entity_id: media_player.samsung_7_series_50
      state: 'on'
    - condition: state
      entity_id: light.tv_lights
      state: 'on'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 30
    target:
      entity_id: light.tv_lights
  mode: single
- id: '1677197404905'
  alias: Turn off all automations when Away
  description: 'Turn off most automation when the Family is away '
  trigger:
  - platform: state
    entity_id:
    - group.family
    to: not_home
    from: home
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: script.interior_off
    data: {}
  mode: single
- id: '1677363387723'
  alias: Big Ben Clock
  description: ''
  trigger:
  - platform: time_pattern
    hours: '0'
  condition:
  - condition: time
    after: '12:00:00'
    before: '22:00:00'
  - condition: or
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.wheatley
    data:
      media_content_id: '{% if now().strftime("%M")|int == 30 %} https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-01.wav
        {% else %} https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
        {% endif %}

        '
      media_content_type: audio/mp4
  mode: single
- id: '1677942364759'
  alias: Notify Boris the Washing room is done.
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_room_wall_plug_power
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 5
  condition: []
  action:
  - service: notify.mobile_app_rufus
    data:
      title: TerryMachine
      message: The washing room is done.
  mode: single
- id: '1678225083143'
  alias: Hallway - Sensor light
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion_2
      include_sun: sun_disabled
      include_zone: zone_enabled
      zone: zone.home
      time_delay: 0
      light_switch:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_cws_806lm_light
      include_bypass: bypass_disabled
      include_time: time_disabled
      before_time: '22:00:00'
      include_night_lights: night_lights_enabled
      night_lights:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_cws_806lm_light
      night_time_delay: 0
      include_night_light_control: use_night_brightness
      night_lights_after_time: 00:00:00
      night_lights_before_time: 07:30:00
      include_light_control: use_brightness
      after_time: 07:30:00
- id: '1678472105494'
  alias: Karel
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tz3000_rco1yzb1_ts004f_switch
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.tz3000_rco1yzb1_ts004f_switch
      state: 'on'
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.woonkamer
    else:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.woonkamer
  mode: single
- id: '1678895798861'
  alias: Boven - Sensor Light
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion_3
      light_switch:
        entity_id: light.bed_light
      include_light_control: use_brightness
      include_time: time_enabled
      after_time: 08:00:00
      include_night_lights: night_lights_enabled
      night_time_delay: 0
      include_night_light_control: use_night_brightness
      night_lights_before_time: 08:00:00
      night_lights:
        entity_id: light.staircase_light
