homeassistant:
  # packages: !include_dir_named packages

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

logger:
  default: info

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'en'
    tld: co.uk
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Matthew
    cache: True

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include_dir_merge_named group

# Example configuration.yaml entry
switch:
  - platform: flux
    lights:
      - light.bed_light
      - light.blake
      - light.boven
      - light.dinner_light
      - light.hannahs_light
      - light.ikea_of_sweden_tradfri_bulb_e27_cws_806lm_light
      - light.staircase_light
      - light.staircase_light
      - light.tv_light
    name: Fluxer
    start_time: "7:00"
    stop_time: "23:00"
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 200
    disable_brightness_adjust: true
    mode: mired
    transition: 30
    interval: 60