
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    language: 'en'
    tld: co.uk

automation: !include_dir_merge_list automation
# automation: !include automations.yaml
group: !include_dir_merge_named group
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
