homeassistant:
  # packages: !include_dir_named packages

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'en'
    tld: co.uk
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Matthew
    cache: True

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml