homeassistant:
  # packages: !include_dir_named packages

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

logger:
  default: info

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'en'
    tld: co.uk
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Matthew
    cache: True

zone:
  # - name: Work
  #   latitude: 32.8753367
  #   longitude: -117.2474053
  # This will override the default home zone
  - name: Home
    latitude: 51.904612
    longitude: 4.455490
    radius: 25
    icon: mdi:account-multiple

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include_dir_merge_named group