demo_google_tts:
  alias: Demo Google TTS
  sequence:
  - service: tts.google_translate_say
    data:
      cache: false
      entity_id: media_player.wheatley
      message: Hello. I am the Google TTS Home Assistant
  mode: single
  icon: mdi:google
demo_amazon_polly_tts:
  alias: Demo Amazon Polly TTS
  sequence:
  - service: tts.amazon_polly_say
    data:
      cache: false
      entity_id: media_player.wheatley
      message: Hello Hannah! You were built to tackle the world. You are not the cheerleader
        for someone else. You are not meant to sit on the sidelines. You were built
        to create your own life and challenge yourself daily. Go out there and tackle
        today, I believe in you!
  mode: single
  icon: mdi:account
