#####################################################################################################
###Script to actually send notifications to the ChromeCast Audios during normal hours and only when we are home! Call like this:
  # action:
    # service: script.speech_engine
    # media_player:
    # speech_message:
# # @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
######################################################################################################

speech_processing:
  mode: queued
  sequence:
    # - service: mqtt.publish
    #   data:
    #     topic: 'polly/lastmsg'
    #     payload: "This message is from {{ now().strftime('%-I') }}:{{ now().strftime('%M') }} {{ now().strftime('%p') }}. {{ speech_message | striptags | truncate(220)}}"
    #     retain: true

    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: group.family
              state: 'home'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'on'
        - condition: or
          conditions:
            - condition: and
              conditions:
                # - condition: state
                #   entity_id: group.bed
                #   state: 'off'
                - condition: time
                  after: '08:00:00'
                  before: '02:00:00'
            - condition: state
              entity_id: input_boolean.alert_mode
              state: 'on'
        - condition: state
          entity_id: input_boolean.speech_notifications
          state: 'on'

    - service: media_player.volume_set
      data:
        entity_id: >
          {{ media_player }}
        volume_level: >-
          {% if now().strftime('%H')|int < 12 and now().strftime('%H')|int > 6 %}
            0.3
          {% elif now().strftime('%H')|int > 12 and now().strftime('%H')|int < 20 %}
            0.5
          {% else %}
            0.3
          {% endif %}

    - service: media_player.play_media
      target:
        entity_id: media_player.wheatley
      data:
        media_content_id: media-source://tts/google_translate?message={{ speech_message }}
        media_content_type: provider
      metadata:
        thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
        media_class: app
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: media-source://tts/google_translate?message={{ speech_message }}

    - service: input_boolean.turn_off
      data:
        entity_id:
          - input_boolean.alert_mode
          # - input_boolean.lastmsg
