######################################################################################################
### Script to shut switches with a 30 second delay to not trample codes
###  Sample Call
#  action:
#   - service: script.switch_turn_off_all
######################################################################################################

switch_turn_off_all:
  sequence:
    - service: switch.turn_off
      entity_id: group.Woonkamer
    - service: switch.turn_off
      entity_id: group.Boven
